---
title: "Star Asia Trading - Prediction of Variable Overhead Costs (Non-Aggregated)"
subtitle: "Accounting Analytics Capstone Project"
author: "Balkis, Jerome Jeevan Naidu, Gavin Ong Ze Kai, Kenneth Tan Yan Hau"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: 
    tufte_variant: "default"
    self_contained: yes
---

```{r Setup, include=FALSE}
library(tufte)
```

```{r Load libraries, message=FALSE,warning=FALSE}

# Load libraries
library(openxlsx) # to load xlsx files
library(tidyverse) # general library for data cleaning
library(lubridate) # for date formatting
library(zoo) # for date formatting
library(corrplot) # to visualise correlation matrix
library(caret) # for cross-validated models
library(glmnet) # for LASSO (Least Absolute Shrinkage and Selection Operator)
library(randomForest) # use varImp in conjunction with caret randomForest output
library(car)# for finding variance inflation factor to deal with multicollinearity
library(coefplot)

```

# 1. Load Files

```{r Load Star Asia Trading files, message=FALSE,warning=FALSE, eval=TRUE}

df3 <- read.xlsx("6. SAT Cleaned_Data Compiled 28 Feb 19 v4.xlsx", sheet = 4, 
                    colNames = TRUE, detectDates = TRUE)
                    # sheet = 4 contains daily variables

```

# 2. Data Cleaning

```{r Data cleaning, message=FALSE,warning=FALSE, eval=TRUE}
# Cleaning and pre-processing



# Change NAs to 0s 
df3[is.na(df3)] <- 0  

```

# 3. Calculation of derived variables

```{r Calculate derived variables, message=FALSE,warning=FALSE, eval=TRUE}

# NaN, Inf to 0s - because some ratios evaluate to NaN or Inf
df3 <- df3 %>%
  mutate_if(is.numeric, funs(replace(., !is.finite(.), 0)))


# Multiply OH/Pair by 1000000 to convert to rupiah
df3 <- df3 %>%
  mutate(variablerupiah = (`OH.COST.COGS.-Variable` / Production) * 1000000)



# Split into test and train data

df3_train <- df3 %>% filter(Date < "2018-06-01")
df3_test <- df3 %>% filter(Date >= "2018-06-01")

```

```{r Linear regression on Variable OH, message=FALSE,warning=FALSE, eval=TRUE}
variables_df3<-as.formula("variablerupiah~P1C1_Sum.of.Output_Assembly+
P1C1_Sum.of.Output_Cut_Sew+P1C1_Sum.of.Target.BEP+
P1C1_Sum.of.EOLR.Target+P1C1_Average.of.EOLR.Gross+
P1C1_Average.of.Working.Hours.Gross+P1C1_Sum.of.Man.Power+
P1C1_Sum.of.Man.Hours.Gross+P1C1_Sum.of.Defect_Cut+
P1C1_Sum.of.Defect_Sew+P1C1_Sum.of.Defect_Assembly+
P1C1_Sum.of.Pass_Reinspection+P1C1_Sum.of.Defect_ReInspection+
P1C1_Sum.of.QtyDowntime+P1C1_Sum.of.Downtime_Seconds+
P1C1_Sum.of.Operating_Time_Sec+P1C2_Sum.of.Output_Assembly+
P1C2_Sum.of.Output_Cut_Sew+P1C2_Sum.of.Target.BEP+
P1C2_Sum.of.EOLR.Target+P1C2_Average.of.EOLR.Gross+
P1C2_Average.of.Working.Hours.Gross+P1C2_Sum.of.Man.Power+
P1C2_Sum.of.Man.Hours.Gross+P1C2_Sum.of.Defect_Cut+
P1C2_Sum.of.Defect_Sew+P1C2_Sum.of.Defect_Assembly+
P1C2_Sum.of.Pass_Reinspection+P1C2_Sum.of.Defect_ReInspection+
P1C2_Sum.of.QtyDowntime+P1C2_Sum.of.Downtime_Seconds+
P1C2_Sum.of.Operating_Time_Sec+P1C3_Sum.of.Output_Assembly+
P1C3_Sum.of.Output_Cut_Sew+P1C3_Sum.of.Target.BEP+
P1C3_Sum.of.EOLR.Target+P1C3_Average.of.EOLR.Gross+
P1C3_Average.of.Working.Hours.Gross+P1C3_Sum.of.Man.Power+
P1C3_Sum.of.Man.Hours.Gross+P1C3_Sum.of.Defect_Cut+
P1C3_Sum.of.Defect_Sew+P1C3_Sum.of.Defect_Assembly+
P1C3_Sum.of.Pass_Reinspection+P1C3_Sum.of.Defect_ReInspection+
P1C3_Sum.of.QtyDowntime+P1C3_Sum.of.Downtime_Seconds+
P1C3_Sum.of.Operating_Time_Sec+P1C4_Sum.of.Output_Assembly+
P1C4_Sum.of.Output_Cut_Sew+P1C4_Sum.of.Target.BEP+
P1C4_Sum.of.EOLR.Target+P1C4_Average.of.EOLR.Gross+
P1C4_Average.of.Working.Hours.Gross+P1C4_Sum.of.Man.Power+
P1C4_Sum.of.Man.Hours.Gross+P1C4_Sum.of.Defect_Cut+
P1C4_Sum.of.Defect_Sew+P1C4_Sum.of.Defect_Assembly+
P1C4_Sum.of.Pass_Reinspection+P1C4_Sum.of.Defect_ReInspection+
P1C4_Sum.of.QtyDowntime+P1C4_Sum.of.Downtime_Seconds+
P1C4_Sum.of.Operating_Time_Sec+P2C1_Sum.of.Output_Assembly+
P2C1_Sum.of.Output_Cut_Sew+P2C1_Sum.of.Target.BEP+
P2C1_Sum.of.EOLR.Target+P2C1_Average.of.EOLR.Gross+
P2C1_Average.of.Working.Hours.Gross+P2C1_Sum.of.Man.Power+
P2C1_Sum.of.Man.Hours.Gross+P2C1_Sum.of.Defect_Cut+
P2C1_Sum.of.Defect_Sew+P2C1_Sum.of.Defect_Assembly+
P2C1_Sum.of.Pass_Reinspection+P2C1_Sum.of.Defect_ReInspection+
P2C1_Sum.of.QtyDowntime+P2C1_Sum.of.Downtime_Seconds+
P2C1_Sum.of.Operating_Time_Sec+P2C2_Sum.of.Output_Assembly+
P2C2_Sum.of.Output_Cut_Sew+P2C2_Sum.of.Target.BEP+
P2C2_Sum.of.EOLR.Target+P2C2_Average.of.EOLR.Gross+
P2C2_Average.of.Working.Hours.Gross+P2C2_Sum.of.Man.Power+
P2C2_Sum.of.Man.Hours.Gross+P2C2_Sum.of.Defect_Cut+
P2C2_Sum.of.Defect_Sew+P2C2_Sum.of.Defect_Assembly+
P2C2_Sum.of.Pass_Reinspection+P2C2_Sum.of.Defect_ReInspection+
P2C2_Sum.of.QtyDowntime+P2C2_Sum.of.Downtime_Seconds+
P2C2_Sum.of.Operating_Time_Sec+P2C3_Sum.of.Output_Assembly+
P2C3_Sum.of.Output_Cut_Sew+P2C3_Sum.of.Target.BEP+
P2C3_Sum.of.EOLR.Target+P2C3_Average.of.EOLR.Gross+
P2C3_Average.of.Working.Hours.Gross+P2C3_Sum.of.Man.Power+
P2C3_Sum.of.Man.Hours.Gross+P2C3_Sum.of.Defect_Cut+
P2C3_Sum.of.Defect_Sew+P2C3_Sum.of.Defect_Assembly+
P2C3_Sum.of.Pass_Reinspection+P2C3_Sum.of.Defect_ReInspection+
P2C3_Sum.of.QtyDowntime+P2C3_Sum.of.Downtime_Seconds+
P2C3_Sum.of.Operating_Time_Sec+P2C4_Sum.of.Output_Assembly+
P2C4_Sum.of.Output_Cut_Sew+P2C4_Sum.of.Target.BEP+
P2C4_Sum.of.EOLR.Target+P2C4_Average.of.EOLR.Gross+
P2C4_Average.of.Working.Hours.Gross+P2C4_Sum.of.Man.Power+
P2C4_Sum.of.Man.Hours.Gross+P2C4_Sum.of.Defect_Cut+
P2C4_Sum.of.Defect_Sew+P2C4_Sum.of.Defect_Assembly+
P2C4_Sum.of.Pass_Reinspection+P2C4_Sum.of.Defect_ReInspection+
P2C4_Sum.of.QtyDowntime+P2C4_Sum.of.Downtime_Seconds+
P2C4_Sum.of.Operating_Time_Sec+P3C1_Sum.of.Output_Assembly+
P3C1_Sum.of.Output_Cut_Sew+P3C1_Sum.of.Target.BEP+
P3C1_Sum.of.EOLR.Target+P3C1_Average.of.EOLR.Gross+
P3C1_Average.of.Working.Hours.Gross+P3C1_Sum.of.Man.Power+
P3C1_Sum.of.Man.Hours.Gross+P3C1_Sum.of.Defect_Cut+
P3C1_Sum.of.Defect_Sew+P3C1_Sum.of.Defect_Assembly+
P3C1_Sum.of.Pass_Reinspection+P3C1_Sum.of.Defect_ReInspection+
P3C1_Sum.of.QtyDowntime+P3C1_Sum.of.Downtime_Seconds+
P3C1_Sum.of.Operating_Time_Sec+P3C2_Sum.of.Output_Assembly+
P3C2_Sum.of.Output_Cut_Sew+P3C2_Sum.of.Target.BEP+
P3C2_Sum.of.EOLR.Target+P3C2_Average.of.EOLR.Gross+
P3C2_Average.of.Working.Hours.Gross+P3C2_Sum.of.Man.Power+
P3C2_Sum.of.Man.Hours.Gross+P3C2_Sum.of.Defect_Cut+
P3C2_Sum.of.Defect_Sew+P3C2_Sum.of.Defect_Assembly+
P3C2_Sum.of.Pass_Reinspection+P3C2_Sum.of.Defect_ReInspection+
P3C2_Sum.of.QtyDowntime+P3C2_Sum.of.Downtime_Seconds+
P3C2_Sum.of.Operating_Time_Sec+P3C3_Sum.of.Output_Assembly+
P3C3_Sum.of.Output_Cut_Sew+P3C3_Sum.of.Target.BEP+
P3C3_Sum.of.EOLR.Target+P3C3_Average.of.EOLR.Gross+
P3C3_Average.of.Working.Hours.Gross+P3C3_Sum.of.Man.Power+
P3C3_Sum.of.Man.Hours.Gross+P3C3_Sum.of.Defect_Cut+
P3C3_Sum.of.Defect_Sew+P3C3_Sum.of.Defect_Assembly+
P3C3_Sum.of.Pass_Reinspection+P3C3_Sum.of.Defect_ReInspection+
P3C3_Sum.of.QtyDowntime+P3C3_Sum.of.Downtime_Seconds+
P3C3_Sum.of.Operating_Time_Sec+P3C4_Sum.of.Output_Assembly+
P3C4_Sum.of.Output_Cut_Sew+P3C4_Sum.of.Target.BEP+
P3C4_Sum.of.EOLR.Target+P3C4_Average.of.EOLR.Gross+
P3C4_Average.of.Working.Hours.Gross+P3C4_Sum.of.Man.Power+
P3C4_Sum.of.Man.Hours.Gross+P3C4_Sum.of.Defect_Cut+
P3C4_Sum.of.Defect_Sew+P3C4_Sum.of.Defect_Assembly+
P3C4_Sum.of.Pass_Reinspection+P3C4_Sum.of.Defect_ReInspection+
P3C4_Sum.of.QtyDowntime+P3C4_Sum.of.Downtime_Seconds+
P3C4_Sum.of.Operating_Time_Sec")
```


```{r LASSO, message=FALSE,warning=FALSE, eval=TRUE}

x <- model.matrix(variables_df3, data = df3_train)[,-1]
y <- model.frame(variables_df3, data = df3_train)[, "variablerupiah"]

LASSO <- cv.glmnet(y = y,        
                  x = x,
                  family = "gaussian",
                  alpha = 1,
                  type.measure = "mse", nfolds = 1000) 


sigvariables <- as.matrix(coef(LASSO, s= "lambda.min"))
write.csv(sigvariables, "non-aggregated variables.csv")

coefplot(LASSO, lambda = "lambda.min", sort = 'magnitude', intercept = FALSE)

# Finding RMSE - error metric for comparison

xvals <- model.matrix(variables_df3, data=df3_test)[,-1]
yvals <- model.frame(variables_df3, data=df3_test)[,"variablerupiah"]

pred_LASSO <- predict(LASSO, xvals, s = "lambda.min", type = "response")

errors_LASSO <- pred_LASSO - df3_test$variablerupiah

MAE_LASSO <- mean(abs(errors_LASSO))
MAE_LASSO

```

```{r Random Forest, message=FALSE,warning=FALSE, eval=TRUE}

set.seed(100)
control <- trainControl(method="repeatedcv", number = 10, repeats = 10)
RF <- train(variables_df3, data = df3_train, method = "rf", preProcess= c("scale", "center"), trControl = control, importance = T)

# Plot variable importance
importance <- varImp(RF)
imp_df2 <- importance$importance
imp_df2$group <- rownames(imp_df2)

imp_df2[order(imp_df2$Overall, decreasing=TRUE)[1:20],] %>%
  ggplot(aes(x = reorder(group, -Overall), y = Overall), size = 2) +
           geom_bar(stat = "identity") + theme(axis.text.x = element_text
                                               (vjust = 1, angle = 90)) +
           labs(x = "Variable", y = "Overall Importance", title = "Scaled 
                Feature Importance")

# Out of sample MAE
pred_RF <- predict(RF, newdata = df3)
error_RF <- pred_RF - df3_test$variablerupiah

MAE_RF <- mean(abs(error_RF))
MAE_RF


```