---
title: "Star Asia Trading - Prediction of Variable Overhead Costs"
subtitle: "Accounting Analytics Capstone Project"
author: "Balkis, Jerome Jeevan Naidu, Gavin Ong Ze Kai, Kenneth Tan Yan Hau"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: 
    tufte_variant: "default"
    self_contained: yes
---

```{r Setup, include=FALSE}
library(tufte)
```

```{r Load libraries, message=FALSE,warning=FALSE}

# Load libraries
library(openxlsx) # to load xlsx files
library(tidyverse) # general library for data cleaning
library(lubridate) # for date formatting
library(zoo) # for date formatting
library(caret) # for cross-validated models
library(glmnet) # for LASSO (Least Absolute Shrinkage and Selection Operator)
library(randomForest) # use varImp in conjunction with caret randomForest output
library(car) # for finding variance inflation factor to deal with multicollinearity
library(coefplot)
```

# 1. Load Files

```{r Load Star Asia Trading files, message=FALSE,warning=FALSE, eval=TRUE}

dailyVar <- read.xlsx("6. SAT Cleaned_Data Compiled 28 Feb 19 v4.xlsx", sheet = 1, 
                    colNames = TRUE, startRow = 3, detectDates = TRUE, cols = 2:26)
                    # sheet = 1 contains daily variables from 
OHcost <- read.xlsx("6. SAT Cleaned_Data Compiled 28 Feb 19 v4.xlsx", sheet = 3,
                    colNames = TRUE, detectDates = TRUE)
                    # sheet = 3 contains monthly overhead figures from fin data
```

# 2. Data Cleaning

```{r Data cleaning, message=FALSE,warning=FALSE, eval=TRUE}
# Cleaning and pre-processing

colnames(OHcost)[1] <- "Date" # Rename "X1" column to "Date
OHcost$YearMon <- as.yearmon(OHcost$Date) # Convert OHCost$Date to year-mon format
dailyVar$Working.Hours.Gross <- as.numeric(dailyVar$Working.Hours.Gross) # convert working hours to numeric

# Remove weekends from data (no work)
dailyVar_WD <- dailyVar[which(weekdays(dailyVar$Date)
         %in% c('Monday','Tuesday', 'Wednesday', 'Thursday', 'Friday')), ]

# Remove dates with output = 0 from dataframe
dailyVar_operating <- dailyVar_WD %>%
  filter(dailyVar_WD$Output_Cut_Sew > 0)

# Change NAs to 0s 
dailyVar_operating[is.na(dailyVar_operating)] <- 0  

```

# 3. Calculation of derived variables

```{r Calculate derived variables, message=FALSE,warning=FALSE, eval=TRUE}
# Calculate derived variables

dailyVar_operating$RFT_Cut <-
  with(dailyVar_operating, (Output_Cut_Sew - Defect_Cut)/Output_Cut_Sew)
dailyVar_operating$RFT_Sew <-
  with(dailyVar_operating, (Output_Cut_Sew - Defect_Sew)/Output_Cut_Sew)
dailyVar_operating$RFT_Assembly <-
  with(dailyVar_operating, (Output_Assembly - Defect_Assembly)/Output_Assembly)
dailyVar_operating$RFT_ReInspection <-
  with(dailyVar_operating, (Pass_Reinspection - Defect_ReInspection)/Output_Assembly)
dailyVar_operating$PPH.Actual.Gross<-
  with(dailyVar_operating, Output_Assembly / Man.Hours.Gross)
dailyVar_operating$Downtime.Percentage <-
  with(dailyVar_operating, Downtime_Seconds / Operating_Time_Sec)

# Split variables that should be summed - e.g. Output, Defect
sum_variables <- subset(dailyVar_operating, select = -c(Target.BEP, 
                                      EOLR.Target, EOLR.Gross,
                                     Working.Hours.Gross, RFT_Cut,
                                     RFT_Sew,           
                                     RFT_Assembly,
                                     RFT_ReInspection,
                                     PPH.Actual.Gross,                      
                                     Downtime.Percentage))

# Split variables that are ratios in nature
avg_variables <- dailyVar_operating[, c("Plant", "Cell", "Date",
                                  "Target.BEP", "EOLR.Target", "EOLR.Gross",
                                  "Working.Hours.Gross", "RFT_Cut",
                                  "RFT_Sew",           
                                  "RFT_Assembly",
                                  "RFT_ReInspection",
                                  "PPH.Actual.Gross",                      
                                  "Downtime.Percentage")]

# Group summed variables into respective year-month and form dataframe
grouped_monthlySumVar <- sum_variables %>%
  group_by(Plant, Cell, as.yearmon(Date)) %>%
  summarise_all(funs(sum))

# Group averaged variables into respective year-month and form dataframe
grouped_monthlyAvgVar <- avg_variables %>%
  group_by(Plant, Cell, as.yearmon(Date)) %>%
  summarise_all(funs(mean))

# merge summed variables and averaged variables
df <- merge(grouped_monthlySumVar, grouped_monthlyAvgVar, 
            by = c("Plant", "Cell", "as.yearmon(Date)"))

df2 <- merge(df, OHcost, by.x = "as.yearmon(Date)", by.y = "YearMon") 

# Rename as.yearmon(date) to Year-Month
colnames(df2)[which(names(df2) == "as.yearmon(Date)")] <- "Year-Month"


# NaN, Inf to 0s - because some ratios evaluate to NaN or Inf
df2 <- df2 %>%
  mutate_if(is.numeric, funs(replace(., !is.finite(.), 0)))

# Multiply OH/Pair by 1000000 to convert to rupiah
df2 <- df2 %>%
  mutate(rupiah = `OH/Pair` * 1000000)

# Derive Variable OH/Pair the same way

df2 <- df2 %>%
  mutate(variablerupiah = (`OH.COST.COGS.-Variable`/ Production) * 1000000)

# Sort df2

df2 <- df2[order(df2$Plant, df2$Cell, df2$`Year-Month`),]

# Split into test and train data

df2_train <- df2 %>% filter(`Year-Month` < "Jun 2018")
df2_test <- df2 %>% filter(`Year-Month` >= "Jun 2018")

```

```{r Linear regression on Variable OH, message=FALSE,warning=FALSE, eval=TRUE}
variables_varOH_1 <- as.formula("variablerupiah ~ 
                           Output_Assembly + 
                           Output_Cut_Sew +
                           Man.Power + 
                           Man.Hours.Gross + 
                           Defect_Cut + 
                           Defect_Sew + 
                           Defect_Assembly + 
                           QtyDowntime +
                           Downtime_Seconds + 
                           Operating_Time_Sec + 
                           Target.BEP +
                           EOLR.Target + 
                           EOLR.Gross + 
                           Working.Hours.Gross + 
                           RFT_Cut+                          
                           RFT_Sew +        
                           RFT_Assembly +
                           RFT_ReInspection +
                           PPH.Actual.Gross +      
                           Downtime.Percentage")

lm_varOH_1 <- lm(variables_varOH_1, data = df2_train)

summary(lm_varOH_1)


# Multicollinearity check
vif(lm_varOH_1)

# Prediction

pred_varOH_1 <- predict(lm_varOH_1, newdata = df2)

df2_test_predicted_vlm <- cbind(df2, pred_varOH_1)

df2_test_average_vlm <- df2_test_predicted_vlm %>%
  group_by(`Year-Month`) %>%
  summarise(PredictedVOH = mean(pred_varOH_1))

# Error metric: Total MAE
df2_actual_vs_pred_vlm <- cbind(df2[1:22,], df2_test_average_vlm)

error_v1 <- df2_actual_vs_pred_vlm$PredictedVOH - df2_actual_vs_pred_vlm$variablerupiah

MAE_lm_v1 <- mean(abs(error_v1))
MAE_lm_v1

# Error metric: Out of sample MAE

error_v1 <- df2_actual_vs_pred_vlm$PredictedVOH[18:22] -     df2_actual_vs_pred_vlm$variablerupiah[18:22]

MAE_lm_v1 <- mean(abs(error_v1))
MAE_lm_v1

```

```{r Second Linear regression on Variable OH, message=FALSE,warning=FALSE, eval=TRUE}
variables_varOH_2 <- as.formula("variablerupiah ~ 
                           Output_Cut_Sew +
                           Man.Power + 
                           Defect_Sew + 
                           Operating_Time_Sec + 
                           EOLR.Gross + 
                           Working.Hours.Gross + 
                           RFT_ReInspection +      
                           Downtime.Percentage")

lm_varOH_2 <- lm(variables_varOH_2, data = df2_train)

summary(lm_varOH_2)

# Multicollinearity check

vif(lm_varOH_2)

# Prediction
pred_varOH_2 <- predict(lm_varOH_2, newdata = df2)


df2_test_predicted_vlm2 <- cbind(df2, pred_varOH_2)

df2_test_average_vlm2 <- df2_test_predicted_vlm2 %>%
  group_by(`Year-Month`) %>%
  summarise(PredictedVOH = mean(pred_varOH_2))

# Error metric: Total MAE
df2_actual_vs_pred_vlm2 <- cbind(df2[1:22,], df2_test_average_vlm2)

error_v2 <- df2_actual_vs_pred_vlm2$PredictedVOH - df2_actual_vs_pred_vlm2$variablerupiah

MAE_lm_v2 <- mean(abs(error_v2))
MAE_lm_v2

# Error metric: Out of sample MAE

error_v2 <- df2_actual_vs_pred_vlm2$PredictedVOH[18:22] -     df2_actual_vs_pred_vlm2$variablerupiah[18:22]

MAE_lm_v2 <- mean(abs(error_v2))
MAE_lm_v2


```

# 6. LASSO model to minimise number of variables

```{r LASSO to find important variables, message=FALSE,warning=FALSE, eval=TRUE}
# LASSO

# Set up matrixes for LASSO since it only accepts matrices
# Model matrix sets up dummy variables for categorical variables 
# Model frame returns a data.frame with variables needed to use the formula 'variables_1' 

x <- model.matrix(variables_varOH_1, data = df2_train)[,-1]
y <- model.frame(variables_varOH_1, data = df2_train)[, "variablerupiah"]

# Set.seed to ensure reproducibility

set.seed(466846)

# cv.glmnet refers to a cross-validated LASSO                                      model when alpha = 1

LASSO <- cv.glmnet(y = y,        
                  x = x,
                  family = "gaussian",
                  alpha = 1,
                  type.measure = "mse", nfolds = 1000) 

plot(LASSO)
coef(LASSO, s= "lambda.min") # shows coefficients of LASSO, including less                                        significant ones
coefplot(LASSO, lambda="lambda.min", sort = 'magnitude') # plot for coefs

# Finding RMSE - error metric for comparison

xvals <- model.matrix(variables_varOH_1, data=df2)[,-1]
yvals <- model.frame(variables_varOH_1, data=df2)[,"variablerupiah"]


# Prediction
pred_LASSO <- predict(LASSO, xvals, s = "lambda.min", type = "response")

df2_test_predicted_LASSO <- cbind(df2, pred_LASSO)

colnames(df2_test_predicted_LASSO)[which(names(df2_test_predicted_LASSO) == "1")] <- "pred_LASSO"

df2_test_average_LASSO <- df2_test_predicted_LASSO %>%
  group_by(`Year-Month`) %>%
  summarise(PredictedOH = mean(pred_LASSO))

# Error metric: Total MAE
df2_actual_vs_pred_LASSO <- cbind(df2[1:22,], df2_test_average_LASSO)

error_LASSO <- df2_actual_vs_pred_LASSO$PredictedOH - df2_actual_vs_pred_LASSO$variablerupiah

MAE_LASSO <- mean(abs(error_LASSO))
MAE_LASSO

# Error metric: Out of sample MAE

error_LASSO <- df2_actual_vs_pred_LASSO$PredictedOH[18:22] -     df2_actual_vs_pred_LASSO$variablerupiah[18:22]

MAE_LASSO <- mean(abs(error_LASSO))
MAE_LASSO

```

# 7. Random Forest model

```{r Random forest, message=FALSE,warning=FALSE, eval=TRUE}
# caret random forest
set.seed(100)
control <- trainControl(method="repeatedcv", number = 10, repeats = 10)
RF <- train(variables_varOH_1, data = df2_train, method = "rf", preProcess= c("scale", "center"), trControl = control, importance = T)

# To plot variable importance graph

importance <- varImp(RF)
imp_df2 <- importance$importance
imp_df2$group <- rownames(imp_df2)

imp_df2 %>%
  ggplot(aes(x = reorder(group, -Overall), y = Overall), size = 2) +
           geom_bar(stat = "identity") + theme(axis.text.x = element_text
                                               (vjust = 1, angle = 90)) +
           labs(x = "Variable", y = "Overall Importance", title = "Scaled 
                Feature Importance")

# Refined model

variables_varOH_3 <- as.formula("variablerupiah ~ 
                           Man.Power + 
                           Man.Hours.Gross + 
                           Defect_Sew + 
                           Defect_Assembly + 
                           Operating_Time_Sec + 
                           Target.BEP +
                           EOLR.Target + 
                           EOLR.Gross + 
                           Working.Hours.Gross + 
                           RFT_Sew +        
                           RFT_Assembly +
                           RFT_ReInspection")

set.seed(100)
control <- trainControl(method="repeatedcv", number = 10, repeats = 10)
RF_2 <- train(variables_varOH_3, data = df2_train, method = "rf", preProcess= c("scale", "center"), trControl = control, importance = T)


# To plot variable importance graph
importance <- varImp(RF_2)
imp_df2 <- importance$importance
imp_df2$group <- rownames(imp_df2)

imp_df2 %>%
  ggplot(aes(x = reorder(group, -Overall), y = Overall), size = 2) +
           geom_bar(stat = "identity") + theme(axis.text.x = element_text
                                               (vjust = 1, angle = 90)) +
           labs(x = "Variable", y = "Overall Importance", title = "Scaled 
                Feature Importance")


# Prediction 
pred_RF_2 <- predict(RF_2, newdata = df2)

df2_test_predicted_RF_2 <- cbind(df2, pred_RF_2)

df2_test_average_RF_2 <- df2_test_predicted_RF_2 %>%
  group_by(`Year-Month`) %>%
  summarise(PredictedVOH = mean(pred_RF_2))

df2_actual_vs_pred_RF_2 <- cbind(df2[1:22,], df2_test_average_RF_2)

# Error metric: Total MAE
error_RF_2 <- df2_actual_vs_pred_RF_2$PredictedVOH - df2_actual_vs_pred_RF_2$variablerupiah

MAE_RF_2 <- mean(abs(error_RF_2))
MAE_RF_2

# Error metric: Out of Sample MAE

error_RF_2 <- df2_actual_vs_pred_RF_2$PredictedVOH[18:22] - df2_actual_vs_pred_RF_2$variablerupiah[18:22]

MAE_RF_2 <- mean(abs(error_RF_2))
MAE_RF_2


```
